# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('avatar', models.ImageField(upload_to='avatars/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blacklist', models.ManyToManyField(blank=True, related_name='_account_blacklist_+', to='bee_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bee_app.Dialog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bee_app.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='dialogs',
            field=models.ManyToManyField(blank=True, related_name='participants', to='bee_app.Dialog'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscribtions',
            field=models.ManyToManyField(blank=True, to='bee_app.Account'),
        ),
    ]
