# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
